// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	STRIPE_SECRET_API_KEY: string;
	STRIPE_METER_NAME_INPUT: string;
	STRIPE_METER_NAME_OUTPUT: string;
	STRIPE_CUSTOMER_ID: string;
	CLAUDE_API_KEY: string;
}
